export default [
  {id:1,title:"Nurse — diet, rest, alcohol awareness",desc:"Monitor diet for lactation. Avoid alcohol. Ensure adequate rest between feeds.",owner:"gail",freq:"daily",cat:"Baby · Feeding",ml:true},
  {id:2,title:"Feeding Log",desc:"Record each feed time and duration. Note any issues with latch or supply.",owner:"gail",freq:"daily",cat:"Baby · Feeding",ml:false},
  {id:3,title:"Express milk — schedule & execute",desc:"Express at scheduled times. Label bags with date/time. Refrigerate immediately.",owner:"gail",freq:"daily",cat:"Baby · Feeding",ml:true},
  {id:4,title:"Milk Audit — stores, expiry & stock",desc:"Check fridge/freezer stocks. Note dates. Plan for upcoming events needing stored milk.",owner:"gail",freq:"weekly",cat:"Baby · Feeding",ml:true},
  {id:5,title:"Sterilisation Cycle",desc:"Sterilise bottles, pump parts and dummies. Use steriliser or boil method. Air dry on clean rack.",owner:"omar",freq:"daily",cat:"Baby · Feeding",ml:false},
  {id:6,title:"Research solids process",desc:"Understand introduction timeline, textures, allergens, BLW vs puree. Document plan.",owner:"gail",freq:"ad-hoc",cat:"Baby · Feeding",ml:true},
  {id:7,title:"Procure solids ingredients",desc:"Buy fresh veg/fruit, appropriate grains and proteins for stage of solids.",owner:"shared",freq:"weekly",cat:"Baby · Feeding",ml:false},
  {id:8,title:"Cook & prepare baby food",desc:"Prepare and portion baby purees or finger foods. Label and freeze extras.",owner:"gail",freq:"weekly",cat:"Baby · Feeding",ml:false},
  {id:9,title:"Feed baby solids meals",desc:"Offer solids at appropriate meal time. Note acceptance, quantities and reactions.",owner:"shared",freq:"daily",cat:"Baby · Feeding",ml:false},
  {id:10,title:"Nap Math",desc:"Calculate wake windows based on age. Plan nap timing around feeds and outings. Adjust daily.",owner:"gail",freq:"daily",cat:"Baby · Sleep & Schedule",ml:true},
  {id:11,title:"Manage day in/out timing",desc:"Coordinate food, nap and milk windows around any planned outings or appointments.",owner:"gail",freq:"daily",cat:"Baby · Sleep & Schedule",ml:true},
  {id:12,title:"Check weather & plan sleep attire",desc:"Check room temp and overnight forecast. Select correct TOG sleep suit. Ensure it's clean.",owner:"gail",freq:"daily",cat:"Baby · Sleep & Schedule",ml:true},
  {id:13,title:"Prepare baby for the day",desc:"Dress, apply morning creams, check nappy. Set up for first activity or feed.",owner:"shared",freq:"daily",cat:"Baby · Sleep & Schedule",ml:false},
  {id:14,title:"Morning shift",desc:"First contact with baby in morning. Nappy, feed, settling. No sleep-ins — includes weekends.",owner:"gail",freq:"daily",cat:"Baby · Sleep & Schedule",ml:false},
  {id:15,title:"Track developmental leaps",desc:"Check Wonder Weeks app. Understand current leap, expected behaviours, best responses.",owner:"gail",freq:"weekly",cat:"Baby · Health & Dev",ml:true},
  {id:16,title:"Research & manage rashes",desc:"Identify rash type. Research appropriate cream. Apply & monitor. Escalate if needed.",owner:"gail",freq:"ad-hoc",cat:"Baby · Health & Dev",ml:true},
  {id:17,title:"Book doctor appointments",desc:"Monitor when vaccines or checkups are due. Book in advance. Prepare question list.",owner:"gail",freq:"ad-hoc",cat:"Baby · Health & Dev",ml:true},
  {id:18,title:"Maintain doctor query list",desc:"Ongoing list of observations, questions and concerns to raise at next appointment.",owner:"gail",freq:"ad-hoc",cat:"Baby · Health & Dev",ml:true},
  {id:19,title:"Manage vaccination responses",desc:"Know what's due. Monitor for fever/reaction post-vax. Have Panadol ready.",owner:"gail",freq:"ad-hoc",cat:"Baby · Health & Dev",ml:true},
  {id:20,title:"Administer baby medicine",desc:"Dose correctly by weight. Record time given. Monitor effectiveness.",owner:"shared",freq:"ad-hoc",cat:"Baby · Health & Dev",ml:false},
  {id:21,title:"Baby education activities",desc:"Plan and deliver stimulation activity appropriate for developmental stage.",owner:"gail",freq:"weekly",cat:"Baby · Health & Dev",ml:true},
  {id:22,title:"Prompt & execute nail trimming",desc:"Check nails weekly. Use baby scissors or file when asleep. Don't forget toes.",owner:"gail",freq:"weekly",cat:"Baby · Health & Dev",ml:false},
  {id:23,title:"Nappy changes — daytime",desc:"Check regularly. Change when wet or soiled. Apply barrier cream if rash-prone.",owner:"shared",freq:"daily",cat:"Baby · Hygiene",ml:false},
  {id:24,title:"Bath — schedule, prep & execute",desc:"Run warm bath. Have towel, PJs and cream ready. Wash with baby-safe wash.",owner:"shared",freq:"daily",cat:"Baby · Hygiene",ml:false},
  {id:25,title:"Apply creams, ointments & washes",desc:"Know which product for which area. Apply after bath and as needed through day.",owner:"gail",freq:"daily",cat:"Baby · Hygiene",ml:true},
  {id:26,title:"Baby laundry",desc:"Soak soiled items immediately. Wash on delicate with baby detergent. Hang, fold, put away.",owner:"gail",freq:"weekly",cat:"Baby · Hygiene",ml:false},
  {id:27,title:"Manage & restock nappy bag",desc:"Check after each outing. Restock nappies, wipes, cream, spare outfit, snacks, milk.",owner:"gail",freq:"weekly",cat:"Baby · Hygiene",ml:true},
  {id:28,title:"Manage baby clothes stock & sizing",desc:"Assess current fit. Pull out next size up. Store outgrown items by size in labelled bags.",owner:"gail",freq:"monthly",cat:"Baby · Clothing & Gear",ml:true},
  {id:29,title:"Procure baby clothes",desc:"Source new items or accept hand-me-downs. Check for next season needs.",owner:"gail",freq:"monthly",cat:"Baby · Clothing & Gear",ml:false},
  {id:30,title:"Research & procure baby consumables",desc:"Track what's running low. Research best products. Order in time to avoid running out.",owner:"gail",freq:"ad-hoc",cat:"Baby · Clothing & Gear",ml:true},
  {id:31,title:"Restock baby consumables",desc:"Regular restock of nappies, wipes, creams, formula (if applicable), bags.",owner:"gail",freq:"weekly",cat:"Baby · Clothing & Gear",ml:false},
  {id:32,title:"Manage nappy sizing & upsizing",desc:"Monitor fit and weight. Move up a size when leaking or gapping starts.",owner:"gail",freq:"monthly",cat:"Baby · Clothing & Gear",ml:true},
  {id:33,title:"Procure toys & equipment",desc:"Research age-appropriate toys. Accept offers from friends. Assess safety.",owner:"gail",freq:"monthly",cat:"Baby · Clothing & Gear",ml:false},
  {id:34,title:"Research & procure pram upgrade",desc:"Assess current pram fit. Research next-stage options. Compare, decide, order.",owner:"gail",freq:"ad-hoc",cat:"Baby · Clothing & Gear",ml:false},
  {id:35,title:"Research & procure car seat upgrade",desc:"Check weight/height limits of current seat. Research next stage. Book installation check.",owner:"omar",freq:"ad-hoc",cat:"Baby · Clothing & Gear",ml:false},
  {id:36,title:"Pack pram for outings",desc:"Food, water, milk, nappies, wipes, cream, spare clothes, sunscreen, hat.",owner:"gail",freq:"ad-hoc",cat:"Baby · Clothing & Gear",ml:true},
  {id:37,title:"Plan & execute days out",desc:"Choose age-appropriate destination. Plan around nap/feed window. Pack accordingly.",owner:"shared",freq:"weekly",cat:"Baby · Activities",ml:false},
  {id:38,title:"Swimming sessions",desc:"Pack swim nappy, towel, change of clothes, snacks. Register for lessons if applicable.",owner:"shared",freq:"weekly",cat:"Baby · Activities",ml:false},
  {id:39,title:"Outing care — napping, feeding, nappy",desc:"Responsible for all baby needs during outing unless explicitly delegated.",owner:"gail",freq:"ad-hoc",cat:"Baby · Activities",ml:true},
  {id:40,title:"Papa time",desc:"Dedicated one-on-one time with Serafina. Gail fully off duty during this window.",owner:"omar",freq:"weekly",cat:"Baby · Activities",ml:false},
  {id:41,title:"Childcare planning & research",desc:"Research options, costs, waitlists in area. Visit centres. Plan start date.",owner:"gail",freq:"ad-hoc",cat:"Baby · Planning",ml:true},
  {id:42,title:"Return to work planning",desc:"Plan return date, childcare logistics, feeding transition, mental prep.",owner:"gail",freq:"ad-hoc",cat:"Baby · Planning",ml:true},
  {id:43,title:"Plan for 2nd child",desc:"Timing, financial implications, pregnancy prep, mental health readiness.",owner:"gail",freq:"ad-hoc",cat:"Baby · Planning",ml:true},
  {id:44,title:"Organise babysitting",desc:"Book sitter in advance. Brief on routine, feeds, contacts. Cook food for parents.",owner:"gail",freq:"ad-hoc",cat:"Baby · Planning",ml:false},
  {id:45,title:"Book Santa photos",desc:"Research session options. Book early (sells out fast). Plan outfit and timing.",owner:"gail",freq:"ad-hoc",cat:"Baby · Planning",ml:false},
  {id:46,title:"Meal planning",desc:"Plan meals for family, baby and grandparents for the week. Check what's in fridge first.",owner:"shared",freq:"weekly",cat:"Household · Food",ml:true},
  {id:47,title:"Grocery shopping",desc:"Use meal plan to build list. Check pantry staples. Order or shop in person.",owner:"shared",freq:"weekly",cat:"Household · Food",ml:false},
  {id:48,title:"Put away shopping",desc:"Unpack groceries. Rotate old stock to front. Refrigerate promptly.",owner:"shared",freq:"weekly",cat:"Household · Food",ml:false},
  {id:49,title:"Cook for Gail & Omar",desc:"Prepare main meals. Cook enough for leftovers. Note dietary needs.",owner:"gail",freq:"daily",cat:"Household · Food",ml:false},
  {id:50,title:"Cook for grandma & grandpa",desc:"Prepare or portion meals when visiting or delivering. Note any dietary restrictions.",owner:"gail",freq:"ad-hoc",cat:"Household · Food",ml:false},
  {id:51,title:"Fridge tidy & clear old food",desc:"Check expiry dates. Discard old food. Wipe down shelves. Note what needs replacing.",owner:"shared",freq:"weekly",cat:"Household · Food",ml:false},
  {id:52,title:"Water System Refill",desc:"Boil fresh water. Filter. Cool. Jug into fridge. Replace filter per schedule. Wash jug weekly.",owner:"omar",freq:"daily",cat:"Household · Food",ml:false},
  {id:53,title:"Cook food for family events",desc:"Plan menu in advance. Prep, cook and pack for event. Cater for all dietary needs.",owner:"gail",freq:"ad-hoc",cat:"Household · Food",ml:false},
  {id:54,title:"Track Omar's water intake",desc:"Monitor Omar is drinking enough. Prompt if needed. Keep water accessible.",owner:"gail",freq:"daily",cat:"Household · Food",ml:false},
  {id:55,title:"General tidy — surfaces & clutter",desc:"Clear benches, fold throws, tidy lounge. 10-min daily reset.",owner:"shared",freq:"daily",cat:"Household · Cleaning",ml:false},
  {id:56,title:"Wash dishes / load dishwasher",desc:"Clear sink. Load dishwasher. Run at end of day. Unstack in morning.",owner:"shared",freq:"daily",cat:"Household · Cleaning",ml:false},
  {id:57,title:"Vacuum — run robot vac",desc:"Clear floor of obstacles. Set robot vac to run. Empty dustbin after.",owner:"shared",freq:"weekly",cat:"Household · Cleaning",ml:false},
  {id:58,title:"Mop floors",desc:"Mop hard floors after vacuuming. Use baby-safe cleaner. Allow to dry before baby is on floor.",owner:"shared",freq:"weekly",cat:"Household · Cleaning",ml:false,weekday:6},
  {id:59,title:"Clean play mat",desc:"Wipe down or wash play mat. Check for debris, sticky patches.",owner:"shared",freq:"weekly",cat:"Household · Cleaning",ml:false},
  {id:60,title:"Bathroom cleaning",desc:"Scrub toilet, basin, shower/bath. Wipe mirror. Replace hand towel. Restock soap.",owner:"shared",freq:"weekly",cat:"Household · Cleaning",ml:false},
  {id:61,title:"Wash towels & floor mats",desc:"Wash on hot. Tumble dry or hang in sun. Return to bathroom when fully dry.",owner:"gail",freq:"weekly",cat:"Household · Cleaning",ml:false},
  {id:62,title:"Change & wash bedsheets",desc:"Strip all beds. Wash. Check weather for line drying. Remake beds same day.",owner:"gail",freq:"weekly",cat:"Household · Cleaning",ml:false},
  {id:63,title:"Run & empty dehumidifier",desc:"Run in damp areas. Empty water tank. Clean filter monthly.",owner:"shared",freq:"weekly",cat:"Household · Cleaning",ml:false},
  {id:64,title:"Open windows & air rooms",desc:"Air each room daily when weather permits. Prioritise baby's room.",owner:"gail",freq:"daily",cat:"Household · Cleaning",ml:false},
  {id:65,title:"Sun cushions, pillows & soft toys",desc:"Put outdoor cushions in sun to freshen. Rotate baby toys in UV when possible.",owner:"gail",freq:"weekly",cat:"Household · Cleaning",ml:false},
  {id:66,title:"Clean appliances — microwave, fridge",desc:"Wipe microwave interior. Clean fridge seal and shelves. Descale kettle monthly.",owner:"shared",freq:"weekly",cat:"Household · Cleaning",ml:false},
  {id:67,title:"Empty kitchen bin to outdoor bins",desc:"Empty when full or before bin night. Replace liner.",owner:"shared",freq:"daily",cat:"Household · Rubbish",ml:false},
  {id:68,title:"Take bins out for collection",desc:"Put correct bins out the night before collection day.",owner:"omar",freq:"weekly",cat:"Household · Rubbish",ml:false,weekday:2},
  {id:69,title:"Bring bins in after collection",desc:"Retrieve bins from kerb same day as collection.",owner:"omar",freq:"weekly",cat:"Household · Rubbish",ml:false,weekday:3},
  {id:70,title:"Gail & Omar laundry — wash & hang",desc:"Sort, wash, hang. Separate delicates. Don't leave in machine overnight.",owner:"shared",freq:"weekly",cat:"Household · Laundry",ml:false},
  {id:71,title:"Bring laundry in",desc:"Bring in once dry. Don't leave overnight or in rain.",owner:"shared",freq:"weekly",cat:"Household · Laundry",ml:false},
  {id:72,title:"Fold & put away clothes",desc:"Fold promptly. Put away in correct drawers/wardrobes. Don't leave in pile.",owner:"shared",freq:"weekly",cat:"Household · Laundry",ml:false},
  {id:73,title:"Replenish toilet basket",desc:"Remove empty rolls. Add new rolls to basket. Check under sink stock.",owner:"gail",freq:"weekly",cat:"Household · Supplies",ml:false},
  {id:74,title:"Procure toilet & bathroom supplies",desc:"Check stocks of TP, soap, shampoo, conditioner, razors. Order before running out.",owner:"gail",freq:"monthly",cat:"Household · Supplies",ml:true},
  {id:75,title:"Procure kitchen supplies",desc:"Check dish soap, sponges, foil, bags, detergent tabs. Reorder as needed.",owner:"gail",freq:"monthly",cat:"Household · Supplies",ml:true},
  {id:76,title:"Charge shared items",desc:"Charge electric toothbrushes, baby monitor, white noise machine, thermometer.",owner:"gail",freq:"weekly",cat:"Household · Supplies",ml:false},
  {id:77,title:"Purchase new toothbrush heads",desc:"Replace heads every 3 months. Check both Gail and Omar's brushes.",owner:"gail",freq:"monthly",cat:"Household · Supplies",ml:false},
  {id:78,title:"Mental load: track & procure anything running low",desc:"Ongoing awareness of all household consumables. Proactively order before empty.",owner:"gail",freq:"ad-hoc",cat:"Household · Supplies",ml:true},
  {id:79,title:"Pay bills & prompt Omar",desc:"Pay all household bills on time. Set reminders. Prompt Omar where needed.",owner:"gail",freq:"monthly",cat:"Household · Admin",ml:true},
  {id:80,title:"Finances — quarterly review",desc:"Review spending, savings, budget vs actuals. Adjust as needed.",owner:"shared",freq:"monthly",cat:"Household · Admin",ml:true},
  {id:81,title:"Renew insurance, shop around",desc:"Review home, contents, health, car. Compare annually. Renew or switch.",owner:"gail",freq:"ad-hoc",cat:"Household · Admin",ml:false},
  {id:82,title:"Credit card management",desc:"Monthly payments on time. Annual review — research better options, renew or switch.",owner:"gail",freq:"monthly",cat:"Household · Admin",ml:false},
  {id:83,title:"Financial advice management",desc:"Manage relationship with advisor. Review recommendations. Track super.",owner:"gail",freq:"ad-hoc",cat:"Household · Admin",ml:true},
  {id:84,title:"Superannuation management",desc:"Monitor contributions and fund performance. Review annually.",owner:"gail",freq:"ad-hoc",cat:"Household · Admin",ml:false},
  {id:85,title:"Tax — gather, prepare & lodge",desc:"Collect receipts. Prepare documents. Lodge by deadline or via accountant.",owner:"gail",freq:"ad-hoc",cat:"Household · Admin",ml:false},
  {id:86,title:"Household services (pest control etc)",desc:"Book annual pest inspection. Coordinate access. Follow up if issues recur.",owner:"gail",freq:"ad-hoc",cat:"Household · Admin",ml:false},
  {id:87,title:"Internet renewal",desc:"Review plan annually. Compare providers. Renew or switch.",owner:"omar",freq:"ad-hoc",cat:"Household · Admin",ml:false},
  {id:88,title:"Manage appliance failures",desc:"When appliances break: research, get quotes, decide repair vs replace, organise installation.",owner:"shared",freq:"ad-hoc",cat:"Household · Admin",ml:false},
  {id:89,title:"Trim lawn",desc:"Mow front and back. Edge borders. Clear clippings. Check after rain.",owner:"omar",freq:"weekly",cat:"Garden",ml:false,weekday:6},
  {id:90,title:"Trim hedges",desc:"Cut back hedges when overgrown. Clear clippings. Check for pest damage.",owner:"omar",freq:"monthly",cat:"Garden",ml:false},
  {id:91,title:"Post-birth recovery",desc:"Pelvic floor exercises daily. Physio appointments. Gradual return to exercise. Monitor nutrition.",owner:"gail",freq:"daily",cat:"Self & Family",ml:false},
  {id:92,title:"Book Omar's doctor & dentist",desc:"Track when appointments are due. Book in advance. Send reminder day before.",owner:"gail",freq:"ad-hoc",cat:"Self & Family",ml:true},
  {id:93,title:"Omar: gym routine",desc:"Maintain regular gym schedule. Communicate timing with Gail for coverage.",owner:"omar",freq:"weekly",cat:"Self & Family",ml:false},
  {id:94,title:"Book date nights",desc:"Research restaurant. Book in advance. Arrange babysitting first.",owner:"gail",freq:"monthly",cat:"Self & Family",ml:false},
  {id:95,title:"Book holidays",desc:"Research destinations, flights, accommodation. Plan around baby's routine and age.",owner:"gail",freq:"ad-hoc",cat:"Self & Family",ml:false},
  {id:96,title:"Think, procure & wrap gifts",desc:"Track birthdays and events. Research appropriate gifts. Buy, wrap and deliver on time.",owner:"gail",freq:"ad-hoc",cat:"Self & Family",ml:true},
  {id:97,title:"Christmas planning",desc:"All gifts (family + friends), stockings, Serafina gift, wrapping, delivery.",owner:"gail",freq:"ad-hoc",cat:"Self & Family",ml:true},
  {id:98,title:"Support Omar's family",desc:"Ma's yoga, Foxtel, shopping, holiday planning. Ongoing care for wider family.",owner:"gail",freq:"ad-hoc",cat:"Self & Family",ml:true},
  {id:99,title:"Prompt household discussions",desc:"Raise key topics: Xmas plan, baby safety, upcoming events, finances, plans.",owner:"shared",freq:"weekly",cat:"Self & Family",ml:true},
];
